setup-environment: detect sourcing in a more robust way
JIRA: EIS-209

Signed-off-by: Christopher Larson <chris_larson@mentor.com>

diff --git a/setup-environment b/setup-environment
--- a/setup-environment
+++ b/setup-environment
@@ -2,9 +2,23 @@
 # SPDX-License-Identifier: MIT
 # ---------------------------------------------------------------------------------------------------------------------
 
-if [ -z "$ZSH_NAME" ] && [ "x$0" = "x./setup-environment" ]; then
-    echo >&2 "Error: This script needs to be sourced. Please run as '. ./setup-environment'"
+flex_sourced=0
+if [ -n "$ZSH_EVAL_CONTEXT" ]; then 
+    case $ZSH_EVAL_CONTEXT in *:file) flex_sourced=1;; esac
+elif [ -n "$BASH_VERSION" ]; then
+    (return 0 2>/dev/null) && flex_sourced=1 
 else
+    echo >&2 "Error: This shell is unsupported. Please use bash or zsh"
+    flex_sourced=2
+fi
+
+if [ "$flex_sourced" -eq 0 ]; then
+    echo >&2 "Error: This script needs to be sourced. Please run as '. \"$0\"'"
+    false
+elif [ "$flex_sourced" -eq 2 ]; then
+    false
+else
+    # shellcheck disable=SC2128
     if [ -n "$BASH_SOURCE" ]; then
         layerdir="$(cd "$(dirname "$BASH_SOURCE")" && pwd -P)"
     elif [ -n "$ZSH_NAME" ]; then
