Update DISTRO as per new branding for Flex OS
This also reverts commit bdd684f045a4b5c26014e70d26d2598ed735d806
which introduced intermediate changes.

This removes "Sokol" keyword from the repository except where the
repository link is mentioned as we are not renaming the repository
name yet.

This changes following DISTRO related overrides:
sokol-flex         -> flex-os
sokol-flex-common  -> flex-common
sokol-flex-distro  -> flex-distro
sokol-flex-staging -> flex-staging
sokol-flex-support -> flex-support

JIRA-ID: SB-23722

Signed-off-by: Haseeb Ashraf <haseeb_ashraf@mentor.com>

diff --git a/scripts/setup-flex-builddir b/scripts/setup-flex-builddir
--- a/scripts/setup-flex-builddir
+++ b/scripts/setup-flex-builddir
@@ -10,7 +10,7 @@
 # version 2.  This program  is licensed "as is" without any warranty of any
 # kind, whether express or implied.
 
-DISTRO="${DISTRO:-sokol-flex}"
+DISTRO="${DISTRO:-flex-os}"
 CORELAYERS="${CORELAYERS:-}"
 OPTIONALLAYERS="${OPTIONALLAYERS-}"
 EXTRAFLEXLAYERS="${EXTRAFLEXLAYERS-${EXTRAMELLAYERS-}}"
@@ -21,7 +21,7 @@ usage () {
     cat >&2 <<END
 Usage: $0 [OPTIONS...] [MACHINE]
 
-When operating from a Sokol Flex OS install, this script will use the template config
+When operating from a Flex OS install, this script will use the template config
 files from the installed BSP. If multiple BSPs are installed, you must specify
 MACHINE, and the script will use the templates from that BSP.
 
@@ -37,10 +37,10 @@ changing its configuration.
 Options:
 
   -b BUILDDIR  Specify the build directory to create (default: 'build')
-  -o FLEXDIR    Specify the root of the Sokol Flex OS install, where you can find bitbake
+  -o FLEXDIR    Specify the root of the Flex OS install, where you can find bitbake
                and the layers
   -p PATHS     Specify colon separated list of paths, where you can find layers
-               in addition to the root of the Sokol Flex OS install (default: empty).
+               in addition to the root of the Flex OS install (default: empty).
                If any path in this list contains wildcards, the list must be quoted
                to avoid wildcard substitution by the shell
   -l LAYERS    Space-separated list of layer names for additional layers you
@@ -243,12 +243,12 @@ setup_builddir () {
                     fi
                     echo "$machine"
                 done | prompt_choice $non_interactive "Select BSP to use" >$tmpdir/machine || {
-                    echo >&2 "Error: unable to prompt for an installed Sokol Flex OS BSP, please specify MACHINE"
+                    echo >&2 "Error: unable to prompt for an installed Flex OS BSP, please specify MACHINE"
                     return 1
                 }
             MACHINE="$(cat "$tmpdir/machine")"
             if [ -z "$MACHINE" ]; then
-                echo >&2 "Error: unable to locate installed Sokol Flex OS BSP, please specify MACHINE"
+                echo >&2 "Error: unable to locate installed Flex OS BSP, please specify MACHINE"
                 return 1
             else
                 TEMPLATECONF=$FLEXDIR/$MACHINE/conf
@@ -280,8 +280,8 @@ setup_builddir () {
     if [ -z "$TEMPLATECONF" ]; then
         if [ -f "$BUILDDIR/conf/templateconf.cfg" ]; then
             TEMPLATECONF="$(cat "$BUILDDIR/conf/templateconf.cfg")"
-        elif [ -e "$layerdir/meta-sokol-flex-distro/conf/templates/default/local.conf.sample" ]; then
-            TEMPLATECONF="$layerdir/meta-sokol-flex-distro/conf/templates/default"
+        elif [ -e "$layerdir/meta-flex-distro/conf/templates/default/local.conf.sample" ]; then
+            TEMPLATECONF="$layerdir/meta-flex-distro/conf/templates/default"
         elif [ -e "$OEROOT/.templateconf" ]; then
             . "$OEROOT/.templateconf"
             # Convert to absolute path
