Adjust for renamed repository (meta-mentor -> meta-sokol-flex)
Signed-off-by: Christopher Larson <chris_larson@mentor.com>

diff --git a/meta-sokol-flex-support/recipes-core/meta/archive-release/runqemu.in b/meta-sokol-flex-support/recipes-core/meta/archive-release/runqemu.in
--- a/meta-sokol-flex-support/recipes-core/meta/archive-release/runqemu.in
+++ b/meta-sokol-flex-support/recipes-core/meta/archive-release/runqemu.in
@@ -8,10 +8,10 @@ scriptdir="$(cd "$(dirname "$0")" && pwd)"
 flexdir="$(cd "$scriptdir/../../.." && pwd)"
 
 if ! which bitbake >/dev/null 2>&1; then
-    if [ -e "$flexdir/manifests" ] && ! [ -e "$flexdir/meta-mentor" ]; then
-        echo >&2 "Unable to run bitbake, please create a workspace by sourcing $flexdir/setup-flex and then source the setup script: . <workspacedir>/meta-mentor/setup-environment"
+    if [ -e "$flexdir/manifests" ] && ! [ -e "$flexdir/meta-sokol-flex" ]; then
+        echo >&2 "Unable to run bitbake, please create a workspace by sourcing $flexdir/setup-flex and then source the setup script: . <workspacedir>/meta-sokol-flex/setup-environment"
     else
-        echo >&2 "Unable to run bitbake, please source the setup script: . $flexdir/meta-mentor/setup-environment"
+        echo >&2 "Unable to run bitbake, please source the setup script: . $flexdir/meta-sokol-flex/setup-environment"
     fi
     exit 1
 fi
